config/routes.rb
Rails.application.routes.draw do
  root 'lessons#index'
  
  devise_for :users
  resources :users
  
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  
  resources :lessons do 
    resources :charges
    resources :classrooms
    
  end
  resources :categories, only: [:show]
  
  resources :lessons do 
    resources :comments
  end

  namespace :admin do 
    root 'base#index'
    resources :users 
    resources :lessons
  end

  get 'static_pages/contact'
  get 'static_pages/about'
  get 'static_pages/faq'
  get 'static_pages/legal_notice'
end

app/models/lesson.rb
class Lesson < ApplicationRecord

    has_many   :classrooms, dependent: :destroy
    has_many   :students, class_name: "User", through: :classrooms
    
    belongs_to :teacher, class_name: "User"

    has_many :comments

    validates :title, presence: {message: "Le titre est nécessaire à la création d'un cours"}
    validates :title, uniqueness: {message: "Ce titre est déja pris, soyez unique"}
    validates :title , length: { in: 6..50 ,message: "Le titre doit contenir entre 6 et 50 caractères"}
    validates :content, presence: {message: "Un contenu est nécessaire à la création d'un cours"}
    validates :content, length: {minimum: 50 ,message: "Le contenu doit contenir au minimum 50 caractères"}
    validates :category, presence: true
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < ApplicationController
    before_action :authenticate_user!, :is_admin?

    def index
        @users = User.all
        @lessons = Lesson.all
    end

    def update 
        @lesson = Lesson.find(params[:id])
        if @lesson.update(checked: true)
            flash[:success] = "Le cours a bien été validé !"
            redirect_to admin_lessons_path
        else 
            flash[:warning] = "Le cours n'a pas été validé !"
            redirect_to admin_lessons_path
        end
    end
end
    


    

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show]
  before_action :is_accessible?, only: [:show]

  def index
    @lessons = Lesson.where(checked: true)
    @users = User.all
  end

  def show
    @comment = Comment.new
    @comments = Comment.all
    @lesson = Lesson.find(params[:id])
    @students = [Lesson.find(params[:id]).students]
  end
  
  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(
      title: params[:lesson][:title], 
      content: params[:lesson][:content],
      category: params[:lesson][:category],
      price: params[:lesson][:price],
      summary: params[:lesson][:summary],
      teacher: current_user)
    if @lesson.save 
      flash[:info] = "Votre cours est en cours de validation !"
      redirect_to root_path
    else
      render "new"
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    Lesson.destroy(@lesson.id)
    if @lesson.destroy 
      flash[:warning] = "Votre cours a bien été supprimé !"
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update(
      title: params[:lesson][:title], 
      content: params[:lesson][:content],
      category: params[:lesson][:category],
      price: params[:lesson][:price],
      summary: params[:lesson][:summary])
      redirect_to @lesson
    else
      render :edit
    end
  end

  private

  def is_accessible?
    @lesson = Lesson.find(params[:id])
    paid_lesson = @lesson.classrooms.map {|c| c.student}.include?(current_user)
    if @lesson.price == 0 || @lesson.price == nil || paid_lesson
    elsif @lesson.teacher.id == current_user.id
    elsif current_user.admin == true
    else
      redirect_to  new_lesson_charge_path(@lesson.id)
    end
  end
end

app/helpers/lesson_helper.rb
module LessonHelper
  def is_student_to_current_lesson(lesson)
    lesson.students.include?(current_user)
  end
end

app/views/admin/lessons/index.html.erb
 <div class="page-header header-filter" data-parallax="true" style="background-color: blue">
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand text-center">
            <h1>Cours de Couture Academy</h1>
            <h3 class="title text-center">Allez on valide ! </h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
      <div class="section text-center">
        <h2 class="title">Nos cours tous jolis tous beaux </h2>
      </div>
      <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
              <ul class="nav nav-pills nav-pills-icons" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active show" href="#home-1" role="tab" data-toggle="tab" aria-selected="true">
                    <i class="material-icons">home</i>
                        Home
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#assignment_returned-1" role="tab" data-toggle="tab" aria-selected="false">
                    <i class="material-icons">assignment_returned</i>
                    Validation 
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#face-1" role="tab" data-toggle="tab" aria-selected="false">
                    <i class="material-icons">face</i>
                    Apprentis
                  </a>
                </li>
              </ul>
              <div class="tab-content tab-space">
                <div class="tab-pane active show" id="home-1">
                  On rentre à la maison ? C'est par <%= link_to "ici", admin_root_path %> !
                </div>
                <div class="tab-pane" id="assignment_returned-1">
                  Administrator vous avez des nouveaux cours à valider !
                  <br><br>Il serait temps de s'en occuper !   <%= link_to "Valider les cours", admin_lessons_path %>
                </div>
                <div class="tab-pane" id="face-1">
                  Administrator, vous pouvez visualiser tous les nouveaux petits couturiers et anciens par la même occasion. 
                  <br><br>N'hésite pas à venir à dire bonjour aux nouveaux ! <%= link_to "Nos Couturiers en herbe", admin_users_path %>
                </div>
              </div>
              </div><br><br> 
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th class="text-center">#</th>
                        <th>Email</th>
                        <th>Titre</th>
                        <th>Catégorie</th>
                        <th> Validations </th>
                        <th class="text-right">Prix</th>
                        <th class="text-right">Actions</th>
                      </tr>
                    </thead>
                    <% @lessons.each do |lesson|%>
                    <tbody>
                        <td class="text-center"><%= lesson.id %></td>
                        <td><%= lesson.teacher.email %></td>
                        <td><%= lesson.title %></td>
                        <td><%= lesson.category %></td>
                        <% if lesson.checked? %>
                        <td class="badge badge-pill badge-success">En ligne</td>
                        <%else%>
                        <td class="badge badge-pill badge-danger">En attente</td>
                        <%end%>
                        <td class="text-right"><%= lesson.price %> € </td>
                        <td class="td-actions text-right">
                          <a  href="<%= lesson_path(lesson.id)%>" rel="tooltip" class="btn btn-info btn-just-icon btn-sm" data-original-title="" title="">
                            <i class="material-icons">description</i>
                          </a>
                          <a   <%= link_to "done_outline" , admin_lesson_path(lesson.id) , data: { toggle: "tooltip", placement: "top", title: "Valider", confirm: "Es-tu sûr-e de vouloir valider ce cours ?"} , method: :put, class:"material-icons btn btn-success btn-sm" %>
                          </a>
                          <a   <%= link_to "exit_to_app" , lesson_path(lesson.id) , data: { toggle: "tooltip", placement: "right", title: "Supprimer", confirm: "Es-tu sûr-e de vouloir supprimer ce cours ?"} , method: :delete, class:"material-icons btn btn-warning btn-sm" %>
                          </a>
                        </td>
                    </tbody>
                    <% end %>
              </table>
    </div>
  </div>
</div>