config/routes.rb
Rails.application.routes.draw do
  root 'lessons#index'
  
  devise_for :users
  resources :users
  
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  
  resources :lessons do 
    resources :charges
    resources :classrooms
    
  end
  resources :categories, only: [:show]
  
  resources :lessons do 
    resources :comments
  end

  namespace :admin do 
    root 'base#index'
    resources :users 
    resources :lessons
  end

  get 'static_pages/contact'
  get 'static_pages/about'
  get 'static_pages/faq'
  get 'static_pages/legal_notice'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable
            
has_one_attached :avatar

has_many :followed_lessons, foreign_key: "student_id", class_name: "Classroom", dependent: :destroy
has_many :lessons, through: :followed_lessons
has_many :taught_lessons,  foreign_key: "teacher_id", class_name: "Lesson", dependent: :destroy

has_many :comments

validates :username, presence: true
validates :username, uniqueness: true

  def is_teacher? 
    if @current_user.taught_lessons.count > 0
    else
    end
  end
  
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :authenticate_user!, :is_admin?
    
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end
    
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        if @user.destroy 
          flash[:warning] = "Le compte a bien été supprimé !"
          redirect_to root_path
        else
          render "new"
        end
    end   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @classrooms = Classroom.where(:student_id => @user.id)
    @taught_lessons = Lesson.where(:teacher_id => @user.id)
  end

  def destroy
    @user = current_user
    @user.destroy
    if @user.destroy 
      flash[:warning] = "Le compte a bien été supprimé !"
      redirect_to root_path
    else
      render "new"
    end
  end

  def new
    @user = User.new
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="page-header header-filter" data-parallax="true" style="background-color: blue">
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand text-center">
            <h1>Nos Couturiers en herbe</h1>
            <h3 class="title text-center">Un peu de tricot, deux belottes de laines et beaucoup d'amour  </h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
      <div class="section text-center">
        <h2 class="title">Prend bien soin de ta communauté Administrator</h2>
      </div>
      <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
              <ul class="nav nav-pills nav-pills-icons" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active show" href="#home-1" role="tab" data-toggle="tab" aria-selected="true">
                    <i class="material-icons">home</i>
                        Home
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#assignment_returned-1" role="tab" data-toggle="tab" aria-selected="false">
                    <i class="material-icons">assignment_returned</i>
                    Validation 
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#face-1" role="tab" data-toggle="tab" aria-selected="false">
                    <i class="material-icons">face</i>
                    Apprentis
                  </a>
                </li>
              </ul>
              <div class="tab-content tab-space">
                <div class="tab-pane active show" id="home-1">
                  On rentre à la maison ? C'est par <%= link_to "ici", admin_root_path %> !
                </div>
                <div class="tab-pane" id="assignment_returned-1">
                  Administrator vous avez des nouveaux cours à valider !
                  <br><br>Il serait temps de s'en occuper !   <%= link_to "Valider les cours", admin_lessons_path %>
                </div>
                <div class="tab-pane" id="face-1">
                  Administrator, vous pouvez visualiser tous les nouveaux petits couturiers et anciens par la même occasion. 
                  <br><br>N'hésite pas à venir à dire bonjour aux nouveaux ! <%= link_to "Nos Couturiers en herbe", admin_users_path %>
                </div>
              </div>
              </div><br><br>
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th class="text-center">#</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Cours fournis</th>
                        <th class="text-right">Cours suivis</th>
                        <th class="text-right">Actions</th>
                      </tr>
                    </thead>
                    <% @users.each do |user|%>
                    <tbody>
                        <td class="text-center"><%= user.id %></td>
                        <td><%= user.username %></td>
                        <td><%= user.email %></td>
                        <td><%= user.taught_lessons.count %> </td>
                        <td class="text-right"><%= Classroom.where(student_id: user.id).count %>   </td>
                        <td class="td-actions text-right">
                          <a  href="<%= user_path(user.id)%>" rel="tooltip" class="btn btn-success btn-just-icon btn-sm" data-original-title="" title="">
                            <i class="material-icons">account_box</i>
                          </a>
                        </td>
                    </tbody>
                    <% end %>
                  </table>
      </div>
  </div>
</div>